import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import GlobalConcierge from "@/components/global-concierge";
import { getSession } from "@/lib/session";
import { StoreInitializer } from "@/lib/session-initializer";
import { Toaster } from "@/components/ui/sonner";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wunkathomes | Ghana's Premier Real Estate Marketplace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionUser = await getSession()
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", figtree.variable)}
    >
      <body className="min-h-full flex flex-col">
        <StoreInitializer user={sessionUser} />
      <div className="print:hidden">
        <Navbar />
      </div>

        {children}
        
      <div className="print:hidden">
        <GlobalConcierge/>
        <Footer/>
      </div>
        <Toaster position="top-right"/>
        </body>
    </html>
  );
}
